# Training Configuration for Standard U-Net
# Fetal Head Segmentation - Standard U-Net Baseline

# Data Paths (Updated for new structure)
data:
  # train_images: 'shared/dataset/training_set/images'
  # train_masks: 'shared/dataset/training_set/masks'
  # val_images: 'shared/dataset/validation_set/images'
  # val_masks: 'shared/dataset/validation_set/masks'
  train_images: 'shared/dataset_v2/training_set/images'
  train_masks: 'shared/dataset_v2/training_set/masks'
  val_images: 'shared/dataset_v2/validation_set/images'
  val_masks: 'shared/dataset_v2/validation_set/masks'

  # test_images: 'shared/dataset/test_set/images'
  # test_masks: 'shared/dataset/test_set/masks'

# Model Architecture
model:
  name: 'StandardUNet'
  in_channels: 1
  out_channels: 1
  base_filters: 64

# Training Hyperparameters
training:
  batch_size: 16
  num_epochs: 100
  num_workers: 4
  pin_memory: true
  early_stopping_patience: 15

  # Optimizer - Standard U-Net uses Adam with lr=1e-4
  optimizer:
    name: 'Adam'
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.0

  # Learning Rate Scheduler
  scheduler:
    name: 'ReduceLROnPlateau'
    mode: 'max'
    factor: 0.5
    patience: 10
    min_lr: 1.0e-6
    verbose: true

# Loss Function
loss:
  name: 'DiceBCELoss'
  dice_weight: 0.8
  bce_weight: 0.2
  smooth: 1.0

# Data Augmentation
# augmentation:
#   train:
#     horizontal_flip:
#       p: 0.5
#     vertical_flip:
#       p: 0.5
#     rotate:
#       limit: 20
#       p: 0.5
#     shift_scale_rotate:
#       shift_limit: 0.1
#       scale_limit: 0.1
#       rotate_limit: 0
#       p: 0.5

#   # Preprocessing (always applied)
#   preprocessing:
#     image_size: [256, 256]
#     normalize: true
#     normalize_method: 'divide_255' # Simple normalization

# Logging and Checkpointing
logging:
  checkpoint_dir: 'accuracy_focus/standard_unet/results/checkpoints'
  log_dir: 'accuracy_focus/standard_unet/results/logs'
  prediction_dir: 'accuracy_focus/standard_unet/results/predictions'
  visualization_dir: 'accuracy_focus/standard_unet/results/visualizations'
  save_every_n_epochs: 10
  save_best_only: true
  visualize_every_n_epochs: 5

# Evaluation Metrics
metrics:
  - 'dice_coefficient'
  - 'iou'
  - 'pixel_accuracy'

# Device
device: 'cuda' # or 'cpu'
