# Training Configuration for Fetal Head Segmentation
# Based on "Precise segmentation of fetal head in ultrasound images using improved U-Net model"

# Data Paths
data:
  train_images: 'dataset/training_set/images'
  train_masks: 'dataset/training_set/masks'
  val_images: 'dataset/validation_set/images'
  val_masks: 'dataset/validation_set/masks'
  test_images: 'dataset/test_set/images'
  test_masks: 'dataset/test_set/masks'
  cache_dir: 'preprocessed_data'
  use_cache: true

# Model Architecture
model:
  name: 'ImprovedUNet'
  in_channels: 1
  out_channels: 1
  base_filters: 64
  # ASPP atrous rates
  aspp_rates: [6, 12, 18]
  # FP+SAM layers
  num_fp_layers: 3

# Training Hyperparameters
training:
  batch_size: 16
  num_epochs: 100
  num_workers: 4
  pin_memory: true
  early_stopping_patience: 15

  # Optimizer
  optimizer:
    name: 'Adam'
    lr: 0.001 # Initial learning rate as specified in reference paper
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.0

  # Learning Rate Scheduler
  scheduler:
    name: 'ReduceLROnPlateau'
    mode: 'max' # 'max' because we monitor val_dice (higher is better)
    factor: 0.5
    patience: 10
    min_lr: 1.0e-6
    verbose: true

  # Loss Function
  loss:
    name: 'DiceBCELoss'
    dice_weight: 0.5
    bce_weight: 0.5

# Data Augmentation
augmentation:
  train:
    horizontal_flip:
      p: 0.5
    rotate:
      limit: 20
      p: 0.5
    shift_scale_rotate:
      shift_limit: 0.1
      scale_limit: 0.1
      rotate_limit: 0
      p: 0.5

  # Preprocessing (always applied)
  preprocessing:
    image_size: [256, 256]
    normalize: true
    normalize_range: [0, 1]

# Validation
validation:
  val_split: 0.1 # 10% of training data for validation
  val_frequency: 1 # Validate every N epochs

# Checkpointing
checkpoint:
  save_dir: 'results/checkpoints'
  save_best: true
  save_last: true
  monitor: 'val_dice' # Metric to monitor for best model
  mode: 'max' # 'max' for metrics like Dice, 'min' for loss

# Logging
logging:
  log_dir: 'results/logs'
  log_frequency: 10 # Log every N batches
  tensorboard: true
  save_predictions: true
  prediction_dir: 'results/predictions'
  visualization_dir: 'results/visualizations'

# Target Performance Metrics
target_metrics:
  dice: 0.9781 # DSC ≥97.81%
  iou: 0.9790 # mIoU ≥97.90%
  pixel_accuracy: 0.9918 # mPA ≥99.18%

# Device
device: 'cuda' # 'cuda' or 'cpu'

# Random Seed (for reproducibility)
seed: 42
